[project]
name = "archive-flattener"
version = "1.0.0"
description = "Flatten ZIP and RAR archives while preserving duplicate filenames."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

authors = [
    { name = "Anshuk Jirli" }
]

keywords = [
    "archive",
    "zip",
    "rar",
    "extractor",
    "filesystem",
    "python",
    "utility"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: System :: Archiving",
    "Topic :: Utilities"
]

dependencies = [
    "rarfile>=4.2"
]